apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: demo-spring-boot-app-k8s
  title: demo-spring-boot-app-k8s
  annotations:
    circleci.com/project-slug: github/piomin/demo-spring-boot-app-k8s
    github.com/project-slug: piomin/demo-spring-boot-app-k8s
    sonarqube.org/project-key: piomin_demo-spring-boot-app-k8s
    backstage.io/kubernetes-id: demo-spring-boot-app-k8s
    argocd/app-name: demo-spring-boot-app-k8s
    prometheus.io/rule: container_memory_usage_bytes{pod=~"demo-spring-boot-app-k8s-.*"}|pod,rate(container_cpu_usage_seconds_total{pod=~"demo-spring-boot-app-k8s-.*"}[5m])|pod
  tags:
    - spring-boot
    - java
    - maven
    - circleci
    - renovate
    - sonarqube
spec:
  type: service
  owner: piotr.minkowski@gmail.com
  lifecycle: experimental